services:
  - type: web
    name: zoomerr-live
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PHONE_NUMBER
        sync: false
      - key: VITE_API_URL
        value: "/"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: PUBLIC_LIVEKIT_URL
        sync: false
